### ISSUE TITLE
can't read dahua streams?

### ISSUE THREAD

**Issue by dannypar** [aler9/rtsp-simple-proxy#10]
with a config:

```
streams:
  furtka:
    url: 'rtsp://user:pass@ipadress:554/cam/realmonitor?channel=1&subtype=0'
    protocol: tcp
```

im getting 404 (not found) response from a proxy

```
2020/06/26 15:18:52 rtsp-simple-proxy v0.3.7
2020/06/26 15:18:52 [UDP/RTP listener] opened on :8052
2020/06/26 15:18:52 [UDP/RTCP listener] opened on :8053
2020/06/26 15:18:52 [TCP listener] opened on :8558
2020/06/26 15:18:52 [STREAM furtka] initializing with protocol tcp
2020/06/26 15:18:52 [STREAM furtka] ERR: OPTIONS returned code 404 (Not Found)
2020/06/26 15:18:53 [RTSP client 10.152.11.23:50093] connected
2020/06/26 15:18:53 [RTSP client 10.152.11.23:50093] OPTIONS
2020/06/26 15:18:53 [RTSP client 10.152.11.23:50093] DESCRIBE
2020/06/26 15:18:53 [RTSP client 10.152.11.23:50093] ERR: stream 'furtka' is not ready yet
2020/06/26 15:18:53 [RTSP client 10.152.11.23:50093] disconnected

```

**Comment by x-jokay** [comment]
Can you check if port `554` is the `TCP` or the `RTSP` port on your camera?

![dahua-ports](https://user-images.githubusercontent.com/18613935/85875299-48c45e80-b7d4-11ea-9e53-4d89930018d5.png)

I am using this config and can confirm it works:

```sh
streams:
  dahua:
    url: rtsp://192.168.1.111:44444/cam/realmonitor?channel=1&subtype=0
    protocol: tcp
```

Just to verify the stream works, you can open the url using [VLC](https://www.videolan.org/vlc/) with enabled option `Use RTP over RTSP (TCP)`.

![vlc-settings](https://user-images.githubusercontent.com/18613935/85875640-d1db9580-b7d4-11ea-8a3f-d4a6e131b053.png)

**Comment by x-jokay** [comment]
And verify if the RTSP url for you model is correct, see [here](https://community.geniusvision.net/platform/cprndr/manurtsp/2299590857000018003).

**Comment by aler9** [comment]
The problem could be different: RTSP is implemented in very different ways, especially in embedded systems like cameras, and in some implementations the OPTIONS command is missing.
I think the address is correct and the proxy is able to connect to the camera, but the OPTIONS command is missing.
I'll try to edit the proxy to make the OPTIONS command optional.

**Comment by dannypar** [comment]
> Can you check if port `554` is the `TCP` or the `RTSP` port on your camera?
> 
> ![dahua-ports](https://user-images.githubusercontent.com/18613935/85875299-48c45e80-b7d4-11ea-9e53-4d89930018d5.png)
> 
> I am using this config and can confirm it works:
> 
> ```shell
> streams:
>   dahua:
>     url: rtsp://user:pass@192.168.1.111:44444/cam/realmonitor?channel=1&subtype=0
>     protocol: tcp
> ```
> 
> Just to verify the stream works, you can open the url using [VLC](https://www.videolan.org/vlc/) with enabled option `Use RTP over RTSP (TCP)`.
> 
> ![vlc-settings](https://user-images.githubusercontent.com/18613935/85875640-d1db9580-b7d4-11ea-8a3f-d4a6e131b053.png)

This is not the case, sadly. I'm using these streams with VLC and Media Player classic without any problems. I believe that as the aler9 wrote, actual connection is made but for some reason stream is considered empty.

**Comment by aler9** [comment]
OPTIONS is now optional.
Please try again with v0.3.8 and let me know. Thanks

**Comment by dannypar** [comment]
> OPTIONS is now optional.
> Please try again with v0.3.8 and let me know. Thanks

That actually did the trick and it works great now. Good job and thanks!
