### ISSUE TITLE
Stream set credentials is not feasible

### ISSUE THREAD

**Issue by andreyvolosyuk** [aler9/rtsp-simple-proxy#2]
Stream set credentials is not feasible cause preliminary OPTIONS request return 401 response (requires digest authentication), it doesn't handle it and returns from function.

https://github.com/aler9/rtsp-simple-proxy/blob/master/stream.go#L220

**Comment by aler9** [comment]
Hi, thanks for the report, this should be fixed in v0.3.1, let me know if there are more problems.
