### ISSUE TITLE
Feature Request: Pre/Post Script

### ISSUE THREAD

**Issue by benbullnz** [aler9/rtsp-simple-proxy#3]
Would it be possible to integrate the run pre/post script feature from rtsp-simple-server into rtsp-simple-proxy? It would be great to use this feature to help keep track of and log the number of connected clients.

Thanks

**Comment by aler9** [comment]
Hi, rtsp-simple-proxy has been merged into rtsp-simple-server, so all rtsp-simple-server features are now available.
