### ISSUE TITLE
Unable to connect to v4l2rtspserver-0.2.0  ERR: expected 'RTSP/1.0', got 

### ISSUE THREAD

**Issue by gustavobsch** [aler9/rtsp-simple-proxy#4]
Connecting to a raspberry camera using v4l2rtspserver I get the following.

Could you please add support? Thanks!

[v4l2rtspserver-connect-fail.zip](https://github.com/aler9/rtsp-simple-proxy/files/4733591/v4l2rtspserver-connect-fail.zip)

2020/06/05 02:24:47 rtsp-simple-proxy v0.3.3
2020/06/05 02:24:47 [UDP/RTP listener] opened on :8050
2020/06/05 02:24:47 [UDP/RTCP listener] opened on :8051
2020/06/05 02:24:47 [TCP listener] opened on :5554
2020/06/05 02:24:47 [STREAM cam1] initializing with protocol tcp
2020/06/05 02:24:47 [STREAM cam1] ERR: expected 'RTSP/1.0', got '$,��Q��f��+olT�*�5h��Q��fcam1$[���W�2��Q��f!�4!��@
                                                                                                                   ڷ�fDIs�ؑ���l�&'

**Comment by aler9** [comment]
Hi, thanks for the report, v4l2rtspserver is now fully supported (v0.3.7).

**Comment by mikegleasonjr** [comment]
I had this problem connecting to a live555 proxy. Will report back too

**Comment by gustavobsch** [comment]
I switched back to ffmpeg since rtsp-proxy would constituently re-connect.

**Comment by mikegleasonjr** [comment]
Connecting to a 555 proxy server I get:

```
$ rtsp-simple-proxy conf.yaml 
2020/06/26 17:10:21 rtsp-simple-proxy v0.0.0
2020/06/26 17:10:21 [UDP/RTP listener] opened on :8050
2020/06/26 17:10:21 [UDP/RTCP listener] opened on :8051
2020/06/26 17:10:21 [TCP listener] opened on :8554
2020/06/26 17:10:21 [STREAM mypath] initializing with protocol udp
2020/06/26 17:10:21 [STREAM mypath] ready
2020/06/26 17:10:27 [STREAM mypath] ERR: stream is dead
```

If using TCP:
```
$ rtsp-simple-proxy conf.yaml 
2020/06/26 17:11:58 rtsp-simple-proxy v0.0.0
2020/06/26 17:11:58 [UDP/RTP listener] opened on :8050
2020/06/26 17:11:58 [UDP/RTCP listener] opened on :8051
2020/06/26 17:11:58 [TCP listener] opened on :8554
2020/06/26 17:11:58 [STREAM mypath] initializing with protocol tcp
2020/06/26 17:11:58 [STREAM mypath] ready
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] connected
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] OPTIONS
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] DESCRIBE
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] SETUP
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] SETUP
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] PLAY
2020/06/26 17:13:01 [RTSP client 127.0.0.1:54166] is receiving on path 'mypath', 2 tracks via udp
2020/06/26 17:13:08 [STREAM mypath] ERR: read tcp 192.168.X.X:45810->192.168.X.X:554: i/o timeout
2020/06/26 17:13:08 [RTSP client 127.0.0.1:54166] ERR: read tcp 127.0.0.1:8554->127.0.0.1:54166: use of closed network connection
2020/06/26 17:13:08 [RTSP client 127.0.0.1:54166] disconnected
2020/06/26 17:13:13 [STREAM mypath] initializing with protocol tcp
2020/06/26 17:13:13 [STREAM mypath] ready
2020/06/26 17:13:14 [RTSP client 127.0.0.1:54170] connected
2020/06/26 17:13:14 [RTSP client 127.0.0.1:54170] disconnected
```

But before I had what the OP had with some random garbage instead of `RTSP/1.0`

Config is minimal:

```
streams:
  mypath:
    url: rtsp://555-proxy-url.lan/proxyStream
    protocol: tcp
```

**Comment by aler9** [comment]
rtsp-simple-proxy has been merged into rtsp-simple-server, this issue has been moved here: https://github.com/aler9/rtsp-simple-server/issues/22
