### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by x-jokay** [aler9/rtsp-simple-proxy#9]
May be others can check this too but compared to other services, the CPU usage for `rtsp-simple-proxy` seems quite high (3 streams setup, no clients connected).

In fact it uses almost as much CPU as the `GitLab` container :roll_eyes: 

But this may be normal for this type of service?

**Comment by x-jokay** [comment]
GitLab CPU usage:

![gitlab](https://user-images.githubusercontent.com/18613935/85324238-c2ed9e00-b4c9-11ea-85d4-96b314106644.png)

rtsp-simple-proxy CPU usage:

![rtsp](https://user-images.githubusercontent.com/18613935/85324257-ca14ac00-b4c9-11ea-9b48-b8f746ad20cd.png)

**Comment by aler9** [comment]
Hi, rtsp-simple-proxy has been merged into rtsp-simple-server, please check again with rtsp-simple-server (the configuration file is really similar) and let me know if CPU usage has decreased.

New issue: https://github.com/aler9/rtsp-simple-server/issues/21
